name: Deploy to generaltest (staging)

on:
  push:
    branches: [ catfix-db ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: da77fd5165dc79f35a5d3c58ca9dc021
          command: pages deploy public --project-name=generaltest --branch=main
